trash: Minor improvements
- Remove unecessary double brackets in `if`
- Remove unecassary invokation of `cmd.exe`
- Redirect output to stderr

diff --git a/Cygwin rm Move to RecycleBin/trash b/Cygwin rm Move to RecycleBin/trash
--- a/Cygwin rm Move to RecycleBin/trash
+++ b/Cygwin rm Move to RecycleBin/trash
@@ -1,30 +1,31 @@
 #! /bin/bash
 #
-# A rm replacement on Cygwin, using Recycle.exe (http://www.maddogsw.com/cmdutils/).
+# A rm replacement on Cygwin, using Recycle.exe (http://www.maddogsw.com/cmdutils/) and toWinPath
+# (https://github.com/davidhcefx/My-Bash-Scripts/tree/master/Convert%20Cygwin%20Path%20toWinPath).
 # Created by davidhcefx, 2019.11.8.
 
 files=()
 retVal=0
 
-if [[ $# == 0 ]]; then
-    cmd.exe /c Recycle /?
+if [ $# -eq 0 ]; then
+    Recycle.exe "/?"
     exit
 fi
 
 for f in "$@"; do
     case "$f" in
-    -r)  # obmit -r
-    ;;
+    -r) ;;  # obmit -r as Recycle doesn't need it
     *)
-        if [[ -e "$f" ]]; then
+        if [ -e "$f" ]; then
             files+=("$(toWinPath "$f")")
         else
-            echo "trash: cannot remove '$f': No such file or directory"
+            echo "trash: cannot remove '$f': No such file or directory" >&2
             retVal=1
         fi
     ;;
     esac
 done
 
-cmd.exe /c Recycle -f "${files[@]}" || retVal=$?
+echo "Removing ${#files[@]} file(s)..." >&2
+Recycle.exe -f "${files[@]}" || retVal=$?
 exit $retVal
